import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL='https://rognyngeoqiqdwyxoggf.supabase.co';
const SUPABASE_KEY='sb_publishable_RMd9xbp2R3bBluCDiopDFg_w4mgFVP-';
const ADMIN_EMAILS=['takayuki.tsuchiya@gmail.com'];
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY); const $=id=>document.getElementById(id); let user=null,events=[],members=[],responses=[],admin=false;
const statusMap={yes:['○','出席'],partial:['△','遅刻・早退'],no:['×','欠席'],maybe:['?','未定'],none:['—','未回答']};
function msg(text,ok=false){$('message').textContent=text||'';$('message').className=ok?'message ok':'message'}
function fmtDate(x){return new Date(x+'T12:00:00').toLocaleDateString('ja-JP',{month:'numeric',day:'numeric',weekday:'short'})}
async function load(){if(!user)return; const [{data:es,error:e1},{data:ms,error:e2},{data:rs,error:e3},{data:cs,error:e4}]=await Promise.all([supabase.from('events').select('*').order('date').order('time'),supabase.from('members').select('*').order('part').order('name'),supabase.from('responses').select('*'),supabase.from('concert_settings').select('title').eq('id','current').maybeSingle()]); if(e1||e2||e3||e4){msg('Supabaseから読み込めませんでした。SQLとRLSを確認してください。');return} events=es||[];members=ms||[];responses=rs||[];admin=ADMIN_EMAILS.includes((user.email||'').toLowerCase()); $('concertTitle').textContent=cs?.title||'第48回定期演奏会'; document.querySelectorAll('.admin-only').forEach(x=>x.hidden=!admin); render()}
function render(){ $('events').innerHTML=events.map(e=>{const mine=responses.find(r=>r.event_id===e.id&&r.member_id===user.id);const s=mine?.status||'none';return `<article class="event"><button class="event-date" data-detail="${e.id}">${fmtDate(e.date)}<small>${e.kind}</small></button><div><h3>${esc(e.title)}</h3><p class="meta">開始 ${e.time.slice(0,5)}　集合 ${e.gather_time.slice(0,5)}　終了 ${e.end_time.slice(0,5)}</p><p>📍 ${esc(e.venue)} ${e.venue_url?`<a href="${escAttr(e.venue_url)}" target="_blank" rel="noreferrer">場所URL ↗</a>`:''}</p></div><div class="actions"><button class="status ${s}" data-response="${e.id}">${statusMap[s][0]} ${statusMap[s][1]}</button></div></article>`}).join(''); $('empty').hidden=events.length>0; document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(events.find(e=>e.id===b.dataset.detail)));document.querySelectorAll('[data-response]').forEach(b=>b.onclick=()=>response(events.find(e=>e.id===b.dataset.response)))}
function detail(e){$('detail').innerHTML=`<h2>${esc(e.title)}</h2><p>${fmtDate(e.date)} / ${e.kind}<br>開始 ${e.time.slice(0,5)}　集合 ${e.gather_time.slice(0,5)}　終了 ${e.end_time.slice(0,5)}<br>📍 ${esc(e.venue)} ${e.venue_url?`<a href="${escAttr(e.venue_url)}" target="_blank" rel="noreferrer">場所のURLを開く ↗</a>`:''}</p><h3>練習メモ</h3><p class="memo">${esc(e.memo)||'メモはありません。'}</p>`;$('detailDialog').showModal()}
function response(e){$('responseTitle').textContent=e.title;const r=responses.find(x=>x.event_id===e.id&&x.member_id===user.id);$('responseForm').dataset.event=e.id;$('responseForm').status.value=r?.status||'none';$('responseForm').note.value=r?.note||'';$('responseDialog').showModal()}
function esc(v=''){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escAttr(v=''){return esc(v)}
$('authBtn').onclick=async()=>{if(user){await supabase.auth.signOut();return}const email=prompt('ログイン用メールアドレス');if(!email)return;const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});msg(error?.message||'ログインリンクをメールに送信しました。',!error)};
$('titleForm').onsubmit=async e=>{e.preventDefault();const title=new FormData(e.currentTarget).get('title');const {error}=await supabase.from('concert_settings').upsert({id:'current',title});if(error)msg(error.message);else{$('titleDialog').close();msg('公演名を保存しました',true);load()}};
$('loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithOtp({email:$('emailInput').value,options:{emailRedirectTo:location.href}});msg(error?.message||'ログインリンクをメールに送信しました。',!error)};
$('refreshBtn').onclick=load; $('addEventBtn').onclick=()=>{ $('eventForm').reset();$('eventDialog').showModal()}; $('adminTitleBtn').onclick=async()=>{const title=prompt('公演名', $('concertTitle').textContent);if(!title)return;const {error}=await supabase.from('concert_settings').upsert({id:'current',title});msg(error?.message||'公演名を保存しました',!error);load()};
$('eventForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.created_by=user.id;const {error}=await supabase.from('events').insert(d);if(error)msg(error.message);else{$('eventDialog').close();msg('日程を保存しました',true);load()}};
$('responseForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const {error}=await supabase.from('responses').upsert({member_id:user.id,event_id:f.dataset.event,status:f.status.value,note:f.note.value});if(error)msg(error.message);else{$('responseDialog').close();msg('出欠を保存しました',true);load()}};
supabase.auth.onAuthStateChange((_event,session)=>{user=session?.user||null;$('userEmail').textContent=user?.email||'未ログイン';$('authBtn').textContent=user?'ログアウト':'ログイン';$('loginPanel').hidden=!!user;$('schedule').hidden=!user;if(user)load()}); const {data:{session}}=await supabase.auth.getSession(); if(session?.user){user=session.user;$('userEmail').textContent=user.email;$('authBtn').textContent='ログアウト';$('loginPanel').hidden=true;$('schedule').hidden=false;load()}
